apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: sante-medical
  labels:
    app: backend
    tier: application
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: backend
  sessionAffinity: None
